### ISSUE TITLE
Powah addon IAP doesnt work with this.

### ISSUE THREAD

**Issue by potpie123** [Hellish-Mods/Powah-Overcharged#7]
it said it requires powah 2.3 or above but says this is powah 1.0.3

**Comment by TheFieryFalcon** [comment]
NOOO WHO ADDED MICROTRANSACTIONS TO POWAH

**Comment by Gcat101** [comment]
Did you test it in an instance?

**Comment by potpie123** [comment]
i tried the client kept failing when the mod was in it but when I took IAP out everything worked fine

**Comment by potpie123** [comment]
![image](https://github.com/Hellish-Mods/Powah-Overcharged/assets/73724870/80627db4-44eb-472a-b6f2-d50392ec3651)

**Comment by Gcat101** [comment]
ah I see the issue

**Comment by potpie123** [comment]
im gonna throw a shot in the dark and say its because of the update of the mod?

**Comment by Gcat101** [comment]
it's because when we forked the mod, we changed the version to 1.0.0 and started counting from there, IAP however, expects regular powah and it's version numbers

**Comment by potpie123** [comment]
Anyway that can be fixed or would it be too difficult to do?

**Comment by Gcat101** [comment]
there are a couple solutions, we can either:
1. Switch back to the powah version scheme or
2. Use a scheme like "2.3o{our version}"

We'll try the second soltuion first, if it doesn't work we'd have to use the first one or do some mixin magic

**Comment by RealRainbuu** [comment]
when I release 1.0 I will switch to 2.3o[1.0], if it doesn't fix I will reopen :)

**Comment by RealRainbuu** [comment]
(i lied its gonna be 1.1)

**Comment by Gcat101** [comment]
reopening cause whoops haha see #8

**Comment by RealRainbuu** [comment]
fixed in 1.1.3
