### ISSUE TITLE
[Crash] Newest update causing mixin crash

### ISSUE THREAD

**Issue by MundM2007** [Hellish-Mods/Powah-Overcharged#9]
**Description**
The Crash occurs just when installing powah overcharged on a clean profile

**Versions**
Forge: 36.2.39
Lollipop: Lollipop-1.16.5-3.2.9.jar
Powah Overcharged: powahovercharged-2.3o1.1.jar

**Logs**
[latest.log](https://github.com/Hellish-Mods/Powah-Overcharged/files/13589223/latest.log)
[debug.log](https://github.com/Hellish-Mods/Powah-Overcharged/files/13589224/debug.log)

**Comment by RealRainbuu** [comment]
Fixed in latest
